#include "display.h"
#include "config.h"
#include "epd_driver.h"
#include "cjk16.h"   // 16x16 CJK dot-matrix (auto-generated by firmware/tools/gen_cjk16.py)
#include <time.h>    // time()/localtime_r for the status-bar date

// ── Unified 5x7 pixel font ─────────────────────────────────
// Each glyph is 5 columns x 7 rows, stored column-major.
// Bit 0 = top row, bit 6 = bottom row.

const uint8_t* getGlyph(char c) {
    // Uppercase letters
    static const uint8_t g_A[] = {0x7E,0x11,0x11,0x11,0x7E};
    static const uint8_t g_B[] = {0x7F,0x49,0x49,0x49,0x36};
    static const uint8_t g_C[] = {0x3E,0x41,0x41,0x41,0x22};
    static const uint8_t g_D[] = {0x7F,0x41,0x41,0x22,0x1C};
    static const uint8_t g_E[] = {0x7F,0x49,0x49,0x49,0x41};
    static const uint8_t g_F[] = {0x7F,0x09,0x09,0x09,0x01};
    static const uint8_t g_G[] = {0x3E,0x41,0x49,0x49,0x3A};
    static const uint8_t g_H[] = {0x7F,0x08,0x08,0x08,0x7F};
    static const uint8_t g_I[] = {0x00,0x41,0x7F,0x41,0x00};
    static const uint8_t g_K[] = {0x7F,0x08,0x14,0x22,0x41};
    static const uint8_t g_L[] = {0x7F,0x40,0x40,0x40,0x40};
    static const uint8_t g_M[] = {0x7F,0x02,0x0C,0x02,0x7F};
    static const uint8_t g_N[] = {0x7F,0x04,0x08,0x10,0x7F};
    static const uint8_t g_O[] = {0x3E,0x41,0x41,0x41,0x3E};
    static const uint8_t g_P[] = {0x7F,0x09,0x09,0x09,0x06};
    static const uint8_t g_R[] = {0x7F,0x09,0x19,0x29,0x46};
    static const uint8_t g_S[] = {0x26,0x49,0x49,0x49,0x32};
    static const uint8_t g_T[] = {0x01,0x01,0x7F,0x01,0x01};
    static const uint8_t g_U[] = {0x3F,0x40,0x40,0x40,0x3F};
    static const uint8_t g_V[] = {0x1F,0x20,0x40,0x20,0x1F};
    static const uint8_t g_W[] = {0x3F,0x40,0x38,0x40,0x3F};
    static const uint8_t g_X[] = {0x63,0x14,0x08,0x14,0x63};
    static const uint8_t g_Y[] = {0x07,0x08,0x70,0x08,0x07};
    static const uint8_t g_Z[] = {0x61,0x51,0x49,0x45,0x43};

    // Lowercase letters
    static const uint8_t g_a[] = {0x20,0x54,0x54,0x54,0x78};
    static const uint8_t g_b[] = {0x7F,0x48,0x44,0x44,0x38};
    static const uint8_t g_c[] = {0x38,0x44,0x44,0x44,0x28};
    static const uint8_t g_d[] = {0x38,0x44,0x44,0x28,0x7F};
    static const uint8_t g_e[] = {0x38,0x54,0x54,0x54,0x18};
    static const uint8_t g_f[] = {0x00,0x08,0x7E,0x09,0x02};
    static const uint8_t g_g[] = {0x18,0xA4,0xA4,0xA4,0x7C};
    static const uint8_t g_h[] = {0x7F,0x08,0x04,0x04,0x78};
    static const uint8_t g_i[] = {0x00,0x44,0x7D,0x40,0x00};
    static const uint8_t g_k[] = {0x7F,0x10,0x28,0x44,0x00};
    static const uint8_t g_l[] = {0x00,0x41,0x7F,0x40,0x00};
    static const uint8_t g_m[] = {0x7C,0x04,0x18,0x04,0x78};
    static const uint8_t g_n[] = {0x7C,0x08,0x04,0x04,0x78};
    static const uint8_t g_o[] = {0x38,0x44,0x44,0x44,0x38};
    static const uint8_t g_p[] = {0x7C,0x14,0x14,0x14,0x08};
    static const uint8_t g_r[] = {0x7C,0x08,0x04,0x04,0x08};
    static const uint8_t g_s[] = {0x48,0x54,0x54,0x54,0x24};
    static const uint8_t g_t[] = {0x04,0x3F,0x44,0x40,0x20};
    static const uint8_t g_u[] = {0x3C,0x40,0x40,0x20,0x7C};
    static const uint8_t g_v[] = {0x1C,0x20,0x40,0x20,0x1C};
    static const uint8_t g_w[] = {0x3C,0x40,0x30,0x40,0x3C};

    // Digits 0-9
    static const uint8_t g_0[] = {0x3E,0x51,0x49,0x45,0x3E};
    static const uint8_t g_1[] = {0x00,0x42,0x7F,0x40,0x00};
    static const uint8_t g_2[] = {0x42,0x61,0x51,0x49,0x46};
    static const uint8_t g_3[] = {0x21,0x41,0x45,0x4B,0x31};
    static const uint8_t g_4[] = {0x18,0x14,0x12,0x7F,0x10};
    static const uint8_t g_5[] = {0x27,0x45,0x45,0x45,0x39};
    static const uint8_t g_6[] = {0x3C,0x4A,0x49,0x49,0x30};
    static const uint8_t g_7[] = {0x01,0x71,0x09,0x05,0x03};
    static const uint8_t g_8[] = {0x36,0x49,0x49,0x49,0x36};
    static const uint8_t g_9[] = {0x06,0x49,0x49,0x29,0x1E};

    // Special characters
    static const uint8_t g_colon[] = {0x00,0x00,0x36,0x36,0x00};
    static const uint8_t g_dash[]  = {0x08,0x08,0x08,0x08,0x08};
    static const uint8_t g_dot[]   = {0x00,0x60,0x60,0x00,0x00};
    static const uint8_t g_slash[] = {0x20,0x10,0x08,0x04,0x02};
    static const uint8_t g_exclam[]= {0x00,0x00,0x5F,0x00,0x00};
    static const uint8_t g_space[] = {0x00,0x00,0x00,0x00,0x00};

    switch (c) {
        // Uppercase
        case 'A': return g_A; case 'B': return g_B; case 'C': return g_C;
        case 'D': return g_D; case 'E': return g_E; case 'F': return g_F;
        case 'G': return g_G; case 'H': return g_H; case 'I': return g_I;
        case 'K': return g_K; case 'L': return g_L; case 'M': return g_M;
        case 'N': return g_N; case 'O': return g_O; case 'P': return g_P;
        case 'R': return g_R; case 'S': return g_S; case 'T': return g_T;
        case 'U': return g_U; case 'V': return g_V; case 'W': return g_W;
        case 'X': return g_X; case 'Y': return g_Y; case 'Z': return g_Z;
        // Lowercase
        case 'a': return g_a; case 'b': return g_b; case 'c': return g_c;
        case 'd': return g_d; case 'e': return g_e; case 'f': return g_f;
        case 'g': return g_g; case 'h': return g_h; case 'i': return g_i;
        case 'k': return g_k; case 'l': return g_l; case 'm': return g_m;
        case 'n': return g_n; case 'o': return g_o; case 'p': return g_p;
        case 'r': return g_r; case 's': return g_s; case 't': return g_t;
        case 'u': return g_u; case 'v': return g_v; case 'w': return g_w;
        // Digits
        case '0': return g_0; case '1': return g_1; case '2': return g_2;
        case '3': return g_3; case '4': return g_4; case '5': return g_5;
        case '6': return g_6; case '7': return g_7; case '8': return g_8;
        case '9': return g_9;
        // Special
        case ':': return g_colon; case '-': return g_dash;
        case '.': return g_dot;   case '/': return g_slash;
        case '!': return g_exclam;
        default:  return g_space;
    }
}

// ── Draw scaled text into imgBuf ────────────────────────────

void drawText(const char *msg, int x, int y, int scale) {
    int rowBytes = W / 8;
    int len = strlen(msg);

    for (int ci = 0; ci < len; ci++) {
        const uint8_t *glyph = getGlyph(msg[ci]);
        int cx = x + ci * (5 * scale + scale);
        for (int col = 0; col < 5; col++) {
            for (int row = 0; row < 7; row++) {
                if (glyph[col] & (1 << row)) {
                    for (int dy = 0; dy < scale; dy++) {
                        for (int dx = 0; dx < scale; dx++) {
                            int px = cx + col * scale + dx;
                            int py = y + row * scale + dy;
                            if (px >= 0 && px < W && py >= 0 && py < H)
                                imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
                        }
                    }
                }
            }
        }
    }
}

// ── Helper: calculate text width in pixels ──────────────────

static int textWidth(int charCount, int scale) {
    return charCount * (5 * scale + scale) - scale;
}

static void fillRect(int x, int y, int w, int h) {
    int rowBytes = W / 8;
    for (int py = y; py < y + h; py++) {
        if (py < 0 || py >= H) continue;
        for (int px = x; px < x + w; px++) {
            if (px < 0 || px >= W) continue;
            imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        }
    }
}

// ── Show WiFi setup screen ──────────────────────────────────

void showSetupScreen(const char *apName) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    fillRect(0, 0, W, H * 12 / 100);
    fillRect(W * 8 / 100, H * 28 / 100, W * 84 / 100, H * 2 / 100);
    fillRect(W * 8 / 100, H * 72 / 100, W * 84 / 100, H * 2 / 100);

    const char *title = "SETUP WIFI";
    int titleScale = (H < 200) ? 2 : 4;
    int titleX = (W - textWidth(strlen(title), titleScale)) / 2;
    int titleY = H * 15 / 100;
    drawText(title, titleX, titleY, titleScale);

    const char *line1 = "CONNECT TO";
    int bodyScale = (H < 200) ? 1 : 2;
    int line1X = (W - textWidth(strlen(line1), bodyScale)) / 2;
    int line1Y = H * 36 / 100;
    drawText(line1, line1X, line1Y, bodyScale);

    int apScale = (H < 200) ? 2 : 3;
    int apX = (W - textWidth(strlen(apName), apScale)) / 2;
    int apY = H * 46 / 100;
    drawText(apName, apX, apY, apScale);

    const char *line3 = "OPEN BROWSER";
    int line3X = (W - textWidth(strlen(line3), bodyScale)) / 2;
    int line3Y = H * 62 / 100;
    drawText(line3, line3X, line3Y, bodyScale);

    epdDisplay(imgBuf);
    Serial.printf("Setup screen shown: %s\n", apName);
}

// ── Show diagnostic screen ──────────────────────────────────

void showDiagnostic(const char *line1, const char *line2, const char *line3, const char *line4) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    int titleScale = (H < 200) ? 2 : 3;
    int bodyScale  = (H < 200) ? 1 : 2;

    int y = H * 10 / 100;
    int lh = 7 * titleScale + titleScale * 2;
    int blh = 7 * bodyScale + bodyScale * 2;

    if (line1 && line1[0]) {
        int x = (W - textWidth(strlen(line1), titleScale)) / 2;
        if (x < 4) x = 4;
        drawText(line1, x, y, titleScale);
        y += lh + 4;
    }

    int infoX = W * 5 / 100;
    if (line2 && line2[0]) {
        drawText(line2, infoX, y, bodyScale);
        y += blh;
    }
    if (line3 && line3[0]) {
        drawText(line3, infoX, y, bodyScale);
        y += blh;
    }
    if (line4 && line4[0]) {
        drawText(line4, infoX, y, bodyScale);
    }

    epdDisplay(imgBuf);
}

// ── Show centered error message ─────────────────────────────

void showError(const char *msg) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    int scale = (H < 200) ? 1 : 2;
    int len = strlen(msg);
    int startX = (W - textWidth(len, scale)) / 2;
    int startY = H / 2 - (7 * scale) / 2;

    drawText(msg, startX, startY, scale);

    epdDisplay(imgBuf);
    Serial.printf("Error shown: %s\n", msg);
}

// ── Update time display (partial refresh) ───────────────────

// Time state (shared with network module)
extern int curHour, curMin, curSec;

static const uint16_t GLYPH_SHEN[16] = {
    0x33FE, 0x1A02, 0x04D4, 0x4988, 0x2964, 0x3244, 0x1446, 0x17F8,
    0x20D0, 0x20D0, 0x6148, 0x2246, 0x2443, 0x2840, 0x0000, 0x0000,
};

static const uint16_t GLYPH_YE[16] = {
    0x0200, 0x0180, 0x0086, 0x7F78, 0x0CC0, 0x08FC, 0x1104, 0x1948,
    0x3328, 0x5290, 0x1490, 0x1060, 0x1070, 0x119C, 0x1607, 0x0000,
};

static const uint16_t GLYPH_LING[16] = {
    0x4060, 0x2044, 0x1BFA, 0x0842, 0x0FFE, 0x1188, 0x1306, 0x24CA,
    0x21FC, 0x6318, 0x2490, 0x2060, 0x21B8, 0x2E0F, 0x0000, 0x0000,
};

static const uint16_t GLYPH_CHEN[16] = {
    0x1FFC, 0x1008, 0x1FF8, 0x1008, 0x1FF8, 0x3FFE, 0x2000, 0x2FF8,
    0x2004, 0x3FFA, 0x248C, 0x2450, 0x27B8, 0x4C0E, 0x0000, 0x0000,
};

static const uint16_t GLYPH_ZAO[16] = {
    0x1008, 0x1FFC, 0x1008, 0x1FF8, 0x1008, 0x1008, 0x1FF8, 0x1188,
    0x0184, 0x7FFE, 0x0180, 0x0180, 0x0180, 0x0180, 0x0000, 0x0000,
};

static const uint16_t GLYPH_SHANG[16] = {
    0x0180, 0x0100, 0x0100, 0x0100, 0x0100, 0x01FC, 0x0100, 0x0100,
    0x0100, 0x0100, 0x0100, 0x0100, 0x7FFE, 0x0000, 0x0000, 0x0000,
};

static const uint16_t GLYPH_WU[16] = {
    0x0800, 0x0C00, 0x0808, 0x1FFC, 0x1180, 0x2180, 0x4180, 0x0184,
    0x7FFE, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180, 0x0000,
};

static const uint16_t GLYPH_ZHONG[16] = {
    0x0180, 0x0100, 0x2104, 0x3FFE, 0x2104, 0x2104, 0x2104, 0x3FFC,
    0x2104, 0x2100, 0x0100, 0x0100, 0x0100, 0x0100, 0x0000, 0x0000,
};

static const uint16_t GLYPH_XIA[16] = {
    0x0006, 0x7FFE, 0x0100, 0x0100, 0x0180, 0x0160, 0x0130, 0x0108,
    0x0104, 0x0100, 0x0100, 0x0100, 0x0100, 0x0100, 0x0000, 0x0000,
};

static const uint16_t GLYPH_BANG[16] = {
    0x0C40, 0x1EF6, 0x1108, 0x1090, 0x37BE, 0x3443, 0x5824, 0x97FE,
    0x1080, 0x10FC, 0x1088, 0x1108, 0x1208, 0x1478, 0x0000, 0x0000,
};

static const uint16_t GLYPH_WAN[16] = {
    0x00C0, 0x7CF8, 0x4910, 0x4A24, 0x4BFE, 0x7D24, 0x4924, 0x49EC,
    0x4934, 0x4850, 0x7850, 0x4892, 0x0312, 0x0C1F, 0x0000, 0x0000,
};

int currentPeriodIndex() {
    if (curHour >= 23 || curHour < 2) return 0;
    if (curHour < 5) return 1;
    if (curHour < 8) return 2;
    if (curHour < 12) return 3;
    if (curHour < 14) return 4;
    if (curHour < 18) return 5;
    if (curHour < 20) return 6;
    return 7;
}

static void periodGlyphs(int period, const uint16_t **left, const uint16_t **right) {
    switch (period) {
        case 0: *left = GLYPH_SHEN;  *right = GLYPH_YE;    return;
        case 1: *left = GLYPH_LING;  *right = GLYPH_CHEN;  return;
        case 2: *left = GLYPH_ZAO;   *right = GLYPH_CHEN;  return;
        case 3: *left = GLYPH_SHANG; *right = GLYPH_WU;    return;
        case 4: *left = GLYPH_ZHONG; *right = GLYPH_WU;    return;
        case 5: *left = GLYPH_XIA;   *right = GLYPH_WU;    return;
        case 6: *left = GLYPH_BANG;  *right = GLYPH_WAN;   return;
        default: *left = GLYPH_YE;   *right = GLYPH_WAN;   return;
    }
}

static void drawGlyph16(uint8_t *buffer, int width, int height, int x, int y, const uint16_t *glyph) {
    int rowBytes = (width + 7) / 8;
    for (int row = 0; row < 16; row++) {
        int py = y + row;
        if (py < 0 || py >= height) continue;
        uint16_t bits = glyph[row];
        for (int col = 0; col < 16; col++) {
            if ((bits & (1 << (15 - col))) == 0) continue;
            int px = x + col;
            if (px < 0 || px >= width) continue;
            buffer[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        }
    }
}

// ── CJK + ASCII mixed rendering (native todo text) ──────────

// Draw one 8x16 half-width ASCII glyph from ascii16 table (same TTF as CJK,
// mono-hinted). bit7 = leftmost column, black = 1. Aligns to the CJK 16px cell.
static void drawAscii16(int x, int y, const uint8_t *g) {
    int rowBytes = W / 8;
    for (int row = 0; row < 16; row++) {
        int py = y + row;
        if (py < 0 || py >= H) continue;
        uint8_t bits = g[row];
        for (int col = 0; col < 8; col++) {
            if (!(bits & (0x80 >> col))) continue;
            int px = x + col;
            if (px < 0 || px >= W) continue;
            imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        }
    }
}

// Draw a single 5x7 ASCII glyph, top-left aligned at (x,y), scaled by `scale`.
static void drawAsciiChar(char c, int x, int y, int scale) {
    const uint8_t *g = getGlyph(c);
    int rowBytes = W / 8;
    for (int col = 0; col < 5; col++) {
        for (int row = 0; row < 7; row++) {
            if (!(g[col] & (1 << row))) continue;
            for (int dy = 0; dy < scale; dy++)
                for (int dx = 0; dx < scale; dx++) {
                    int px = x + col * scale + dx;
                    int py = y + row * scale + dy;
                    if (px >= 0 && px < W && py >= 0 && py < H)
                        imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
                }
        }
    }
}

// Pure-ASCII text with NO CJK top offset — used for reminder time / pagination
// small text where bottom-alignment within a 16px cell would push it off-row.
static void drawAsciiText(int x, int y, const char *text, int scale) {
    if (!text) return;
    if (scale < 1) scale = 1;
    int cx = x;
    for (const char *p = text; *p; p++) {
        drawAsciiChar(*p, cx, y, scale);
        cx += 5 * scale + 1;                  // glyph + 1px gap
    }
}

// 16x16 hollow box used when a codepoint is missing from cjk16.h.
static void drawMissingGlyph(int x, int y) {
    int rowBytes = W / 8;
    for (int i = 0; i < 16; i++) {
        int px, py;
        px = x + i; py = y;       if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        px = x + i; py = y + 15;  if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        px = x;     py = y + i;   if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        px = x + 15; py = y + i;  if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
    }
}

// Mixed CJK + ASCII text on a 16px cell grid. ASCII now uses the mono-hinted
// half-width 8x16 ascii16 glyphs (same TTF as CJK), so Chinese and English share
// the same stroke weight. asciiScale is kept for signature compat but no longer
// scales ASCII (the half-width glyph is fixed 8x16). CJK misses render as a box.
void drawMixed(int x, int y, const char *text, int asciiScale) {
    if (!text) return;
    if (asciiScale < 1) asciiScale = 1;
    int cx = x;
    const unsigned char *p = (const unsigned char *)text;
    while (*p) {
        if (*p < 0x80) {                                   // ASCII (half-width 8x16)
            const uint8_t *ag = ascii16_lookup(*p);
            if (ag) drawAscii16(cx, y, ag);
            cx += 9;                                        // 8px glyph + 1px gap
            p += 1;
        } else if ((*p & 0xE0) == 0xC0 && p[1]) {          // 2-byte UTF-8
            uint32_t cp = ((uint32_t)(p[0] & 0x1F) << 6) | (p[1] & 0x3F);
            const uint16_t *gl = cjk16_lookup(cp);
            if (gl) drawGlyph16(imgBuf, W, H, cx, y, gl);
            else    drawMissingGlyph(cx, y);
            cx += 17;                                       // 16 + 1px gap
            p += 2;
        } else if ((*p & 0xF0) == 0xE0 && p[1] && p[2]) {  // 3-byte UTF-8
            uint32_t cp = ((uint32_t)(p[0] & 0x0F) << 12) |
                          ((uint32_t)(p[1] & 0x3F) << 6) | (p[2] & 0x3F);
            const uint16_t *gl = cjk16_lookup(cp);
            if (gl) drawGlyph16(imgBuf, W, H, cx, y, gl);
            else    drawMissingGlyph(cx, y);
            cx += 17;
            p += 3;
        } else {
            p += 1;                                         // skip malformed byte
        }
    }
}

// Pixel width of text as drawn by drawMixed (pass the same asciiScale).
int measureMixed(const char *text, int asciiScale) {
    if (!text) return 0;
    if (asciiScale < 1) asciiScale = 1;
    int cx = 0;
    const unsigned char *p = (const unsigned char *)text;
    while (*p) {
        if (*p < 0x80) { cx += 9; p += 1; }               // half-width 8 + 1px gap
        else if ((*p & 0xE0) == 0xC0 && p[1]) { cx += 17; p += 2; }
        else if ((*p & 0xF0) == 0xE0 && p[1] && p[2]) { cx += 17; p += 3; }
        else { p += 1; }
    }
    return cx > 0 ? cx - 1 : 0;
}

static void drawPeriodLabel(
    uint8_t *buffer,
    int bufferWidth,
    int bufferHeight,
    int regionX,
    int regionY,
    int regionWidth,
    int regionHeight
) {
    const uint16_t *left = nullptr;
    const uint16_t *right = nullptr;
    periodGlyphs(currentPeriodIndex(), &left, &right);

    const int glyphW = 16;
    const int glyphH = 16;
    const int gap = 2;
    int startX = regionX + (regionWidth - (glyphW * 2 + gap)) / 2;
    int startY = regionY + (regionHeight - glyphH) / 2;
    if (startX < 0) startX = 0;
    if (startY < 0) startY = 0;

    drawGlyph16(buffer, bufferWidth, bufferHeight, startX, startY, left);
    drawGlyph16(buffer, bufferWidth, bufferHeight, startX + glyphW + gap, startY, right);
}

void updateTimeDisplay() {
    int rgnPixelW = TIME_RGN_X1 - TIME_RGN_X0;
    int rgnW = rgnPixelW / 8;
    int rgnH = TIME_RGN_Y1 - TIME_RGN_Y0;
    drawPeriodLabel(imgBuf, W, H, TIME_RGN_X0, TIME_RGN_Y0, rgnPixelW, rgnH);
    uint8_t partBuf[rgnW * rgnH];
    memset(partBuf, 0xFF, sizeof(partBuf));
    drawPeriodLabel(partBuf, rgnPixelW, rgnH, 0, 0, rgnPixelW, rgnH);
    epdPartialDisplay(partBuf, TIME_RGN_X0, TIME_RGN_Y0, TIME_RGN_X1, TIME_RGN_Y1);
}

// ── Mode preview screen (double-click transition) ───────────

void showModePreview(const char *modeName) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    int nameScale = (H < 200) ? 2 : 3;
    int loadScale = (H < 200) ? 1 : 2;

    int len = strlen(modeName);
    int nameX = (W - textWidth(len, nameScale)) / 2;
    int nameY = H / 2 - (H < 200 ? 15 : 30);
    drawText(modeName, nameX, nameY, nameScale);

    const char *loading = "loading...";
    int loadLen = strlen(loading);
    int loadX = (W - textWidth(loadLen, loadScale)) / 2;
    int loadY = H / 2 + (H < 200 ? 10 : 20);
    drawText(loading, loadX, loadY, loadScale);

    epdDisplayFast(imgBuf);
    Serial.printf("Mode preview shown: %s\n", modeName);
}

// ── Smart display with hybrid refresh strategy ──────────────
// Uses fast refresh (0xC7 + temperature LUT, ~1.5s, minimal flash) most of the time.
// Performs a full refresh (0xF7, clears ghosting) every FULL_REFRESH_INTERVAL cycles.

static int refreshCount = 0;

void smartDisplay(const uint8_t *image) {
    // RLCD: every refresh is an equal full repaint (no fast/full LUT distinction,
    // no ghosting). The cycle counter is kept for API parity with e-ink builds.
    if (refreshCount % FULL_REFRESH_INTERVAL == 0) {
        Serial.printf("smartDisplay: full repaint (cycle %d)\n", refreshCount);
        epdDisplay(image);
    } else {
        Serial.printf("smartDisplay: fast repaint (cycle %d)\n", refreshCount);
        epdDisplayFast(image);
    }
    refreshCount++;
}

// ── UI chrome: status bar / 7-seg clock / todo rows / footer ──
// Three fixed layers (top status bar, middle todo list, bottom footer),
// pixel / ink style: pure black-on-white, thin solid rules, dashed dividers.

#define UI_SB_H   52      // status bar height
#define UI_FT_H   18      // footer height
#define UI_ROW_H  30      // todo row height
#define UI_PER_PAGE 7     // todo items per page

// Hollow rectangle outline (thin 1px rule).
static void outlineRect(int x, int y, int w, int h) {
    int rowBytes = W / 8;
    for (int xx = x; xx < x + w; xx++) {
        if (y >= 0 && y < H)        imgBuf[y*(rowBytes) + xx/8] &= ~(0x80 >> (xx%8));
        if (y+h-1 >= 0 && y+h-1 < H) imgBuf[(y+h-1)*(rowBytes) + xx/8] &= ~(0x80 >> (xx%8));
    }
    for (int yy = y; yy < y + h; yy++) {
        if (x >= 0 && x < W)         imgBuf[yy*(rowBytes) + x/8] &= ~(0x80 >> (x%8));
        if (x+w-1 >= 0 && x+w-1 < W) imgBuf[yy*(rowBytes) + (x+w-1)/8] &= ~(0x80 >> ((x+w-1)%8));
    }
}

// ── pixel fill helper ───────────────────────────────────────
static void segFill(int x, int y, int sw, int sh) {
    int rowBytes = W / 8;
    for (int yy = y; yy < y + sh; yy++)
        for (int xx = x; xx < x + sw; xx++) {
            int px = x + xx, py = y + yy;
            if (px >= 0 && px < W && py >= 0 && py < H)
                imgBuf[py*rowBytes + px/8] &= ~(0x80 >> (px%8));
        }
}

// ── Pixel icons ─────────────────────────────────────────────
static void drawClipboard(int x, int y) {
    outlineRect(x+2, y+3, 13, 14);                 // board
    segFill(x+4, y, 9, 4);                          // clip top
    for (int xx = x+2; xx < x+15; xx++)             // board header line
        if (y+6 >= 0 && y+6 < H) imgBuf[(y+6)*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
}

static void drawBattery(int x, int y, int pct) {
    outlineRect(x, y+2, 22, 12);                    // shell
    segFill(x+22, y+5, 2, 6);                       // positive nub
    int fillw = (pct * 18) / 100;
    if (fillw > 18) fillw = 18;
    if (fillw < 2)  fillw = 2;
    segFill(x+2, y+4, fillw, 8);                    // charge level
}

static void drawCheckbox(int x, int y, bool checked) {
    outlineRect(x, y, 14, 14);
    if (checked) {                                  // simple check mark
        int pts[][2] = {{3,9},{4,10},{5,11},{6,10},{7,9},{8,8},{9,7},{10,6},{11,5},{5,7},{6,7},{7,7},{8,7}};
        int n = (int)(sizeof(pts) / sizeof(pts[0]));
        for (int k = 0; k < n; k++) {
            int px = x + pts[k][0], py = y + pts[k][1];
            if (px >= 0 && px < W && py >= 0 && py < H)
                imgBuf[py*(W/8) + px/8] &= ~(0x80 >> (px%8));
        }
    }
}

static void drawMiniList(int x, int y) {
    for (int r = 0; r < 3; r++) {
        outlineRect(x, y+r*6, 4, 4);
        int yy = y + r*6 + 2;
        for (int xx = x+6; xx < x+14; xx++)
            if (yy >= 0 && yy < H) imgBuf[yy*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
    }
}

static const char *WEEKDAY_CN[7] = {
    "星期日","星期一","星期二","星期三","星期四","星期五","星期六"
};

// ── Status bar ──────────────────────────────────────────────
static void drawStatusBar(int batteryPct) {
    drawClipboard(4, 6);
    // Clock + date both read from the system RTC (kept accurate by syncNTP).
    time_t now = time(nullptr);
    struct tm ti; localtime_r(&now, &ti);
    int lineY = (UI_SB_H - 16) / 2;            // vertically center the 16px line
    // Clock as plain half-width ASCII "HH:MM" (same size as body text)
    char hhmm[6];
    snprintf(hhmm, sizeof(hhmm), "%02d:%02d", ti.tm_hour, ti.tm_min);
    int cx = 26;
    for (char *p = hhmm; *p; p++) {
        const uint8_t *g = ascii16_lookup((uint8_t)*p);
        if (g) drawAscii16(cx, lineY, g);
        cx += 9;
    }
    // date: 月/日 星期X (right of the clock, same baseline; 16px CJK + 8px ASCII)
    char date[32];
    snprintf(date, sizeof(date), "%02d/%02d %s",
             ti.tm_mon + 1, ti.tm_mday, WEEKDAY_CN[ti.tm_wday % 7]);
    drawMixed(cx + 6, lineY, date, 1);
    // battery
    drawBattery(W - 26, 9, batteryPct);
    // separator rule under status bar
    for (int xx = 0; xx < W; xx++)
        if (UI_SB_H >= 0 && UI_SB_H < H) imgBuf[UI_SB_H*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
}

// ── Todo list (middle) ──────────────────────────────────────
static void drawTodoList(const TodoItem *items, int count) {
    int y0 = UI_SB_H + 4;
    for (int i = 0; i < count; i++) {
        int rowTop = y0 + i * UI_ROW_H;
        drawCheckbox(8, rowTop + (UI_ROW_H - 14) / 2, items[i].done);
        // body text (CJK+ASCII), truncate so it never collides with remind time
        int maxW = W - 30 - 58 - 6;
        String t = String(items[i].text);
        while (measureMixed(t.c_str(), 2) > maxW && t.length() > 1)
            t = t.substring(0, t.length() - 1);
        drawMixed(30, rowTop + (UI_ROW_H - 16) / 2, t.c_str(), 2);
        // reminder time (right aligned, pure ASCII, no CJK top offset)
        if (items[i].remind) {
            int rw = measureMixed(items[i].remind, 1);
            drawAsciiText(W - 6 - rw - 1, rowTop + (UI_ROW_H - 7) / 2, items[i].remind, 1);
        }
        // dashed divider between rows
        if (i < count - 1)
            for (int xx = 8; xx < W - 6; xx += 4)
                if (rowTop + UI_ROW_H - 5 >= 0 && rowTop + UI_ROW_H - 5 < H)
                    imgBuf[(rowTop + UI_ROW_H - 5)*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
    }
}

// ── Footer ──────────────────────────────────────────────────
static void drawFooter() {
    int fy = H - UI_FT_H;
    for (int xx = 0; xx < W; xx++)
        if (fy >= 0 && fy < H) imgBuf[fy*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
    drawMiniList(8, H - 15);
    drawMixed(16, H - 16, "待办", 1);
    drawMixed(W - 6 - measureMixed("— 诸事有序", 1) - 1, H - 16, "— 诸事有序", 1);
}

// ── Composite native todo screen ────────────────────────────
void renderTodoScreen(const TodoItem *items, int count, int page, int totalPages, int batteryPct) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);
    drawStatusBar(batteryPct);
    drawTodoList(items, count);
    drawFooter();
    // pagination hint (bottom-right of content area, pure ASCII, no offset)
    char pg[16];
    snprintf(pg, sizeof(pg), "%d / %d", page + 1, totalPages);
    int pgw = measureMixed(pg, 1);
    drawAsciiText(W - 6 - pgw - 1, H - UI_FT_H - 14, pg, 1);
    smartDisplay(imgBuf);
}
