#include "display.h"
#include "config.h"
#include "epd_driver.h"
#include "cjk16.h"   // 16x16 CJK dot-matrix (auto-generated by firmware/tools/gen_cjk16.py)
#include <time.h>    // time()/localtime_r for the status-bar date
#include <WiFi.h>    // WiFi.macAddress() / WiFi.SSID() for the settings menu

// ── Unified 5x7 pixel font ─────────────────────────────────
// Each glyph is 5 columns x 7 rows, stored column-major.
// Bit 0 = top row, bit 6 = bottom row.

const uint8_t* getGlyph(char c) {
    // Uppercase letters
    static const uint8_t g_A[] = {0x7E,0x11,0x11,0x11,0x7E};
    static const uint8_t g_B[] = {0x7F,0x49,0x49,0x49,0x36};
    static const uint8_t g_C[] = {0x3E,0x41,0x41,0x41,0x22};
    static const uint8_t g_D[] = {0x7F,0x41,0x41,0x22,0x1C};
    static const uint8_t g_E[] = {0x7F,0x49,0x49,0x49,0x41};
    static const uint8_t g_F[] = {0x7F,0x09,0x09,0x09,0x01};
    static const uint8_t g_G[] = {0x3E,0x41,0x49,0x49,0x3A};
    static const uint8_t g_H[] = {0x7F,0x08,0x08,0x08,0x7F};
    static const uint8_t g_I[] = {0x00,0x41,0x7F,0x41,0x00};
    static const uint8_t g_K[] = {0x7F,0x08,0x14,0x22,0x41};
    static const uint8_t g_L[] = {0x7F,0x40,0x40,0x40,0x40};
    static const uint8_t g_M[] = {0x7F,0x02,0x0C,0x02,0x7F};
    static const uint8_t g_N[] = {0x7F,0x04,0x08,0x10,0x7F};
    static const uint8_t g_O[] = {0x3E,0x41,0x41,0x41,0x3E};
    static const uint8_t g_P[] = {0x7F,0x09,0x09,0x09,0x06};
    static const uint8_t g_R[] = {0x7F,0x09,0x19,0x29,0x46};
    static const uint8_t g_S[] = {0x26,0x49,0x49,0x49,0x32};
    static const uint8_t g_T[] = {0x01,0x01,0x7F,0x01,0x01};
    static const uint8_t g_U[] = {0x3F,0x40,0x40,0x40,0x3F};
    static const uint8_t g_V[] = {0x1F,0x20,0x40,0x20,0x1F};
    static const uint8_t g_W[] = {0x3F,0x40,0x38,0x40,0x3F};
    static const uint8_t g_X[] = {0x63,0x14,0x08,0x14,0x63};
    static const uint8_t g_Y[] = {0x07,0x08,0x70,0x08,0x07};
    static const uint8_t g_Z[] = {0x61,0x51,0x49,0x45,0x43};

    // Lowercase letters
    static const uint8_t g_a[] = {0x20,0x54,0x54,0x54,0x78};
    static const uint8_t g_b[] = {0x7F,0x48,0x44,0x44,0x38};
    static const uint8_t g_c[] = {0x38,0x44,0x44,0x44,0x28};
    static const uint8_t g_d[] = {0x38,0x44,0x44,0x28,0x7F};
    static const uint8_t g_e[] = {0x38,0x54,0x54,0x54,0x18};
    static const uint8_t g_f[] = {0x00,0x08,0x7E,0x09,0x02};
    static const uint8_t g_g[] = {0x18,0xA4,0xA4,0xA4,0x7C};
    static const uint8_t g_h[] = {0x7F,0x08,0x04,0x04,0x78};
    static const uint8_t g_i[] = {0x00,0x44,0x7D,0x40,0x00};
    static const uint8_t g_k[] = {0x7F,0x10,0x28,0x44,0x00};
    static const uint8_t g_l[] = {0x00,0x41,0x7F,0x40,0x00};
    static const uint8_t g_m[] = {0x7C,0x04,0x18,0x04,0x78};
    static const uint8_t g_n[] = {0x7C,0x08,0x04,0x04,0x78};
    static const uint8_t g_o[] = {0x38,0x44,0x44,0x44,0x38};
    static const uint8_t g_p[] = {0x7C,0x14,0x14,0x14,0x08};
    static const uint8_t g_r[] = {0x7C,0x08,0x04,0x04,0x08};
    static const uint8_t g_s[] = {0x48,0x54,0x54,0x54,0x24};
    static const uint8_t g_t[] = {0x04,0x3F,0x44,0x40,0x20};
    static const uint8_t g_u[] = {0x3C,0x40,0x40,0x20,0x7C};
    static const uint8_t g_v[] = {0x1C,0x20,0x40,0x20,0x1C};
    static const uint8_t g_w[] = {0x3C,0x40,0x30,0x40,0x3C};

    // Digits 0-9
    static const uint8_t g_0[] = {0x3E,0x51,0x49,0x45,0x3E};
    static const uint8_t g_1[] = {0x00,0x42,0x7F,0x40,0x00};
    static const uint8_t g_2[] = {0x42,0x61,0x51,0x49,0x46};
    static const uint8_t g_3[] = {0x21,0x41,0x45,0x4B,0x31};
    static const uint8_t g_4[] = {0x18,0x14,0x12,0x7F,0x10};
    static const uint8_t g_5[] = {0x27,0x45,0x45,0x45,0x39};
    static const uint8_t g_6[] = {0x3C,0x4A,0x49,0x49,0x30};
    static const uint8_t g_7[] = {0x01,0x71,0x09,0x05,0x03};
    static const uint8_t g_8[] = {0x36,0x49,0x49,0x49,0x36};
    static const uint8_t g_9[] = {0x06,0x49,0x49,0x29,0x1E};

    // Special characters
    static const uint8_t g_colon[] = {0x00,0x00,0x36,0x36,0x00};
    static const uint8_t g_dash[]  = {0x08,0x08,0x08,0x08,0x08};
    static const uint8_t g_dot[]   = {0x00,0x60,0x60,0x00,0x00};
    static const uint8_t g_slash[] = {0x20,0x10,0x08,0x04,0x02};
    static const uint8_t g_exclam[]= {0x00,0x00,0x5F,0x00,0x00};
    static const uint8_t g_space[] = {0x00,0x00,0x00,0x00,0x00};

    switch (c) {
        // Uppercase
        case 'A': return g_A; case 'B': return g_B; case 'C': return g_C;
        case 'D': return g_D; case 'E': return g_E; case 'F': return g_F;
        case 'G': return g_G; case 'H': return g_H; case 'I': return g_I;
        case 'K': return g_K; case 'L': return g_L; case 'M': return g_M;
        case 'N': return g_N; case 'O': return g_O; case 'P': return g_P;
        case 'R': return g_R; case 'S': return g_S; case 'T': return g_T;
        case 'U': return g_U; case 'V': return g_V; case 'W': return g_W;
        case 'X': return g_X; case 'Y': return g_Y; case 'Z': return g_Z;
        // Lowercase
        case 'a': return g_a; case 'b': return g_b; case 'c': return g_c;
        case 'd': return g_d; case 'e': return g_e; case 'f': return g_f;
        case 'g': return g_g; case 'h': return g_h; case 'i': return g_i;
        case 'k': return g_k; case 'l': return g_l; case 'm': return g_m;
        case 'n': return g_n; case 'o': return g_o; case 'p': return g_p;
        case 'r': return g_r; case 's': return g_s; case 't': return g_t;
        case 'u': return g_u; case 'v': return g_v; case 'w': return g_w;
        // Digits
        case '0': return g_0; case '1': return g_1; case '2': return g_2;
        case '3': return g_3; case '4': return g_4; case '5': return g_5;
        case '6': return g_6; case '7': return g_7; case '8': return g_8;
        case '9': return g_9;
        // Special
        case ':': return g_colon; case '-': return g_dash;
        case '.': return g_dot;   case '/': return g_slash;
        case '!': return g_exclam;
        default:  return g_space;
    }
}

// ── Draw scaled text into imgBuf ────────────────────────────

// Forward decl: ascii18 proportional glyph renderer (defined below).
static void drawAscii18(int x, int y, const uint32_t *g, int scale);

// drawText now renders with the ascii18 proportional font (Inter @18px) scaled by
// integer `scale`. `y` is the cap-top row (uppercase top). Only ASCII 0x20-0x7E
// is supported here — use drawMixed() for CJK text.
void drawText(const char *msg, int x, int y, int scale) {
    if (!msg) return;
    if (scale < 1) scale = 1;
    int cx = x;
    for (const char *p = msg; *p; p++) {
        uint8_t c = (uint8_t)*p;
        if (c < ASCII18_FIRST || c > ASCII18_LAST) { cx += 6 * scale; continue; }
        const uint32_t *g = ascii18_lookup(c);
        if (g) drawAscii18(cx, y - ASCII18_CAP * scale, g, scale);
        cx += ascii18_width[c - ASCII18_FIRST] * scale + scale;
    }
}

// ── Helper: measured pixel width of an ASCII string in the ascii18 font ──

static int asciiTextWidth(const char *text, int scale) {
    if (!text) return 0;
    if (scale < 1) scale = 1;
    int w = 0;
    for (const char *p = text; *p; p++) {
        uint8_t c = (uint8_t)*p;
        if (c < ASCII18_FIRST || c > ASCII18_LAST) { w += 6 * scale; continue; }
        w += ascii18_width[c - ASCII18_FIRST] * scale + scale;
    }
    return w > 0 ? w - scale : 0;
}

static void fillRect(int x, int y, int w, int h) {
    int rowBytes = W / 8;
    for (int py = y; py < y + h; py++) {
        if (py < 0 || py >= H) continue;
        for (int px = x; px < x + w; px++) {
            if (px < 0 || px >= W) continue;
            imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        }
    }
}

// ── Show WiFi setup screen ──────────────────────────────────

void showSetupScreen(const char *apName) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    fillRect(0, 0, W, H * 12 / 100);
    fillRect(W * 8 / 100, H * 28 / 100, W * 84 / 100, H * 2 / 100);
    fillRect(W * 8 / 100, H * 72 / 100, W * 84 / 100, H * 2 / 100);

    const char *title = "SETUP WIFI";
    int titleScale = (H < 200) ? 1 : 2;
    int titleX = (W - asciiTextWidth(title, titleScale)) / 2;
    int titleY = H * 15 / 100;
    drawText(title, titleX, titleY, titleScale);

    const char *line1 = "CONNECT TO";
    int bodyScale = 1;
    int line1X = (W - asciiTextWidth(line1, bodyScale)) / 2;
    int line1Y = H * 36 / 100;
    drawText(line1, line1X, line1Y, bodyScale);

    int apScale = (H < 200) ? 1 : 2;
    int apX = (W - asciiTextWidth(apName, apScale)) / 2;
    int apY = H * 46 / 100;
    drawText(apName, apX, apY, apScale);

    const char *line3 = "OPEN BROWSER";
    int line3X = (W - asciiTextWidth(line3, bodyScale)) / 2;
    int line3Y = H * 62 / 100;
    drawText(line3, line3X, line3Y, bodyScale);

    epdDisplay(imgBuf);
    Serial.printf("Setup screen shown: %s\n", apName);
}

// ── Show diagnostic screen ──────────────────────────────────

void showDiagnostic(const char *line1, const char *line2, const char *line3, const char *line4) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    int titleScale = (H < 200) ? 1 : 2;
    int bodyScale  = 1;

    int y = H * 10 / 100;
    int lh = 22 * titleScale;
    int blh = 24 * bodyScale;

    if (line1 && line1[0]) {
        int x = (W - asciiTextWidth(line1, titleScale)) / 2;
        if (x < 4) x = 4;
        drawText(line1, x, y, titleScale);
        y += lh + 4;
    }

    int infoX = W * 5 / 100;
    if (line2 && line2[0]) {
        drawText(line2, infoX, y, bodyScale);
        y += blh;
    }
    if (line3 && line3[0]) {
        drawText(line3, infoX, y, bodyScale);
        y += blh;
    }
    if (line4 && line4[0]) {
        drawText(line4, infoX, y, bodyScale);
    }

    epdDisplay(imgBuf);
}

// ── Show centered error message ─────────────────────────────

void showError(const char *msg) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    int scale = 1;
    int startX = (W - asciiTextWidth(msg, scale)) / 2;
    int startY = H / 2 - (20 * scale) / 2;

    drawText(msg, startX, startY, scale);

    epdDisplay(imgBuf);
    Serial.printf("Error shown: %s\n", msg);
}

// ── Update time display (partial refresh) ───────────────────

// Time state (shared with network module)
extern int curHour, curMin, curSec;

static const uint16_t GLYPH_SHEN[16] = {
    0x33FE, 0x1A02, 0x04D4, 0x4988, 0x2964, 0x3244, 0x1446, 0x17F8,
    0x20D0, 0x20D0, 0x6148, 0x2246, 0x2443, 0x2840, 0x0000, 0x0000,
};

static const uint16_t GLYPH_YE[16] = {
    0x0200, 0x0180, 0x0086, 0x7F78, 0x0CC0, 0x08FC, 0x1104, 0x1948,
    0x3328, 0x5290, 0x1490, 0x1060, 0x1070, 0x119C, 0x1607, 0x0000,
};

static const uint16_t GLYPH_LING[16] = {
    0x4060, 0x2044, 0x1BFA, 0x0842, 0x0FFE, 0x1188, 0x1306, 0x24CA,
    0x21FC, 0x6318, 0x2490, 0x2060, 0x21B8, 0x2E0F, 0x0000, 0x0000,
};

static const uint16_t GLYPH_CHEN[16] = {
    0x1FFC, 0x1008, 0x1FF8, 0x1008, 0x1FF8, 0x3FFE, 0x2000, 0x2FF8,
    0x2004, 0x3FFA, 0x248C, 0x2450, 0x27B8, 0x4C0E, 0x0000, 0x0000,
};

static const uint16_t GLYPH_ZAO[16] = {
    0x1008, 0x1FFC, 0x1008, 0x1FF8, 0x1008, 0x1008, 0x1FF8, 0x1188,
    0x0184, 0x7FFE, 0x0180, 0x0180, 0x0180, 0x0180, 0x0000, 0x0000,
};

static const uint16_t GLYPH_SHANG[16] = {
    0x0180, 0x0100, 0x0100, 0x0100, 0x0100, 0x01FC, 0x0100, 0x0100,
    0x0100, 0x0100, 0x0100, 0x0100, 0x7FFE, 0x0000, 0x0000, 0x0000,
};

static const uint16_t GLYPH_WU[16] = {
    0x0800, 0x0C00, 0x0808, 0x1FFC, 0x1180, 0x2180, 0x4180, 0x0184,
    0x7FFE, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180, 0x0000,
};

static const uint16_t GLYPH_ZHONG[16] = {
    0x0180, 0x0100, 0x2104, 0x3FFE, 0x2104, 0x2104, 0x2104, 0x3FFC,
    0x2104, 0x2100, 0x0100, 0x0100, 0x0100, 0x0100, 0x0000, 0x0000,
};

static const uint16_t GLYPH_XIA[16] = {
    0x0006, 0x7FFE, 0x0100, 0x0100, 0x0180, 0x0160, 0x0130, 0x0108,
    0x0104, 0x0100, 0x0100, 0x0100, 0x0100, 0x0100, 0x0000, 0x0000,
};

static const uint16_t GLYPH_BANG[16] = {
    0x0C40, 0x1EF6, 0x1108, 0x1090, 0x37BE, 0x3443, 0x5824, 0x97FE,
    0x1080, 0x10FC, 0x1088, 0x1108, 0x1208, 0x1478, 0x0000, 0x0000,
};

static const uint16_t GLYPH_WAN[16] = {
    0x00C0, 0x7CF8, 0x4910, 0x4A24, 0x4BFE, 0x7D24, 0x4924, 0x49EC,
    0x4934, 0x4850, 0x7850, 0x4892, 0x0312, 0x0C1F, 0x0000, 0x0000,
};

// 16x16 WiFi icon (3 nested arcs + center dot). Black = 1.
static const uint16_t GLYPH_WIFI[16] = {
    0x0300, 0x0480, 0x0840, 0x1020, 0x2010, 0x4008, 0x0000, 0x0C30,
    0x1008, 0x2004, 0x0FF0, 0x0000, 0x0000, 0x0000, 0x0180, 0x0180,
};

int currentPeriodIndex() {
    if (curHour >= 23 || curHour < 2) return 0;
    if (curHour < 5) return 1;
    if (curHour < 8) return 2;
    if (curHour < 12) return 3;
    if (curHour < 14) return 4;
    if (curHour < 18) return 5;
    if (curHour < 20) return 6;
    return 7;
}

static void periodGlyphs(int period, const uint16_t **left, const uint16_t **right) {
    switch (period) {
        case 0: *left = GLYPH_SHEN;  *right = GLYPH_YE;    return;
        case 1: *left = GLYPH_LING;  *right = GLYPH_CHEN;  return;
        case 2: *left = GLYPH_ZAO;   *right = GLYPH_CHEN;  return;
        case 3: *left = GLYPH_SHANG; *right = GLYPH_WU;    return;
        case 4: *left = GLYPH_ZHONG; *right = GLYPH_WU;    return;
        case 5: *left = GLYPH_XIA;   *right = GLYPH_WU;    return;
        case 6: *left = GLYPH_BANG;  *right = GLYPH_WAN;   return;
        default: *left = GLYPH_YE;   *right = GLYPH_WAN;   return;
    }
}

static void drawGlyph16(uint8_t *buffer, int width, int height, int x, int y, const uint16_t *glyph) {
    int rowBytes = (width + 7) / 8;
    for (int row = 0; row < 16; row++) {
        int py = y + row;
        if (py < 0 || py >= height) continue;
        uint16_t bits = glyph[row];
        for (int col = 0; col < 16; col++) {
            if ((bits & (1 << (15 - col))) == 0) continue;
            int px = x + col;
            if (px < 0 || px >= width) continue;
            buffer[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        }
    }
}

// ── CJK + ASCII mixed rendering (native todo text) ──────────

// Draw one proportional ASCII glyph from the ascii18 table (Inter TTF @18px).
// Each row is a uint32_t scanline, bit(ASCII18_W-1)=leftmost column, black=1.
// `scale` = integer magnification (1 = native 20px cell). `y` is the top row of
// the cell; callers that want the cap top at Y should pass Y - ASCII18_CAP*scale.
static void drawAscii18(int x, int y, const uint32_t *g, int scale) {
    if (scale < 1) scale = 1;
    int rowBytes = W / 8;
    for (int row = 0; row < ASCII18_H; row++) {
        for (int col = 0; col < ASCII18_W; col++) {
            if (!(g[row] & (1u << (ASCII18_W - 1 - col)))) continue;
            for (int dy = 0; dy < scale; dy++)
                for (int dx = 0; dx < scale; dx++) {
                    int px = x + col * scale + dx;
                    int py = y + row * scale + dy;
                    if (px >= 0 && px < W && py >= 0 && py < H)
                        imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
                }
        }
    }
}

// Pure-ASCII text in the ascii18 font. `y` is the cap-top row (same convention as
// drawMixed's CJK top), so ASCII drawn here bottom-aligns with adjacent CJK text.
static void drawAsciiText(int x, int y, const char *text, int scale) {
    if (!text) return;
    if (scale < 1) scale = 1;
    int cx = x;
    for (const char *p = text; *p; p++) {
        uint8_t c = (uint8_t)*p;
        if (c < ASCII18_FIRST || c > ASCII18_LAST) { cx += 6 * scale; continue; }
        const uint32_t *g = ascii18_lookup(c);
        if (g) drawAscii18(cx, y - ASCII18_CAP * scale, g, scale);
        cx += ascii18_width[c - ASCII18_FIRST] * scale + scale;
    }
}

// 16x16 hollow box used when a codepoint is missing from cjk16.h.
static void drawMissingGlyph(int x, int y) {
    int rowBytes = W / 8;
    for (int i = 0; i < 16; i++) {
        int px, py;
        px = x + i; py = y;       if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        px = x + i; py = y + 15;  if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        px = x;     py = y + i;   if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
        px = x + 15; py = y + i;  if (px >= 0 && px < W && py >= 0 && py < H) imgBuf[py * rowBytes + px / 8] &= ~(0x80 >> (px % 8));
    }
}

// Mixed CJK + ASCII text. CJK is a 16px grid; ASCII uses the proportional ascii18
// font (Inter @18px, cap-height ~14px) so English/digits look visually level with
// the 16px Chinese instead of small. ASCII is drawn with its cap top aligned to
// the CJK top (y - ASCII18_CAP), so both share a common visual top/baseline.
// Stepping is cx += ascii18_width[cp] + 1 (advance already includes side bearings).
void drawMixed(int x, int y, const char *text, int asciiScale) {
    if (!text) return;
    if (asciiScale < 1) asciiScale = 1;
    int cx = x;
    const unsigned char *p = (const unsigned char *)text;
    while (*p) {
        if (*p < 0x80) {                                   // ASCII (ascii18 proportional)
            const uint32_t *ag = ascii18_lookup(*p);
            if (ag) drawAscii18(cx, y - ASCII18_CAP, ag, 1);
            cx += ascii18_width[*p - ASCII18_FIRST] + 1;   // advance + 1px gap
            p += 1;
        } else if ((*p & 0xE0) == 0xC0 && p[1]) {          // 2-byte UTF-8
            uint32_t cp = ((uint32_t)(p[0] & 0x1F) << 6) | (p[1] & 0x3F);
            const uint16_t *gl = cjk16_lookup(cp);
            if (gl) drawGlyph16(imgBuf, W, H, cx, y, gl);
            else    drawMissingGlyph(cx, y);
            cx += 17;                                       // 16 + 1px gap
            p += 2;
        } else if ((*p & 0xF0) == 0xE0 && p[1] && p[2]) {  // 3-byte UTF-8
            uint32_t cp = ((uint32_t)(p[0] & 0x0F) << 12) |
                          ((uint32_t)(p[1] & 0x3F) << 6) | (p[2] & 0x3F);
            const uint16_t *gl = cjk16_lookup(cp);
            if (gl) drawGlyph16(imgBuf, W, H, cx, y, gl);
            else    drawMissingGlyph(cx, y);
            cx += 17;
            p += 3;
        } else {
            p += 1;                                         // skip malformed byte
        }
    }
}

// Pixel width of text as drawn by drawMixed (pass the same asciiScale).
int measureMixed(const char *text, int asciiScale) {
    if (!text) return 0;
    if (asciiScale < 1) asciiScale = 1;
    int cx = 0;
    const unsigned char *p = (const unsigned char *)text;
    while (*p) {
        if (*p < 0x80) { cx += ascii18_width[*p - ASCII18_FIRST] + 1; p += 1; }   // ascii18 advance + 1px gap
        else if ((*p & 0xE0) == 0xC0 && p[1]) { cx += 17; p += 2; }
        else if ((*p & 0xF0) == 0xE0 && p[1] && p[2]) { cx += 17; p += 3; }
        else { p += 1; }
    }
    return cx > 0 ? cx - 1 : 0;
}

static void drawPeriodLabel(
    uint8_t *buffer,
    int bufferWidth,
    int bufferHeight,
    int regionX,
    int regionY,
    int regionWidth,
    int regionHeight
) {
    const uint16_t *left = nullptr;
    const uint16_t *right = nullptr;
    periodGlyphs(currentPeriodIndex(), &left, &right);

    const int glyphW = 16;
    const int glyphH = 16;
    const int gap = 2;
    int startX = regionX + (regionWidth - (glyphW * 2 + gap)) / 2;
    int startY = regionY + (regionHeight - glyphH) / 2;
    if (startX < 0) startX = 0;
    if (startY < 0) startY = 0;

    drawGlyph16(buffer, bufferWidth, bufferHeight, startX, startY, left);
    drawGlyph16(buffer, bufferWidth, bufferHeight, startX + glyphW + gap, startY, right);
}

void updateTimeDisplay() {
    int rgnPixelW = TIME_RGN_X1 - TIME_RGN_X0;
    int rgnW = rgnPixelW / 8;
    int rgnH = TIME_RGN_Y1 - TIME_RGN_Y0;
    drawPeriodLabel(imgBuf, W, H, TIME_RGN_X0, TIME_RGN_Y0, rgnPixelW, rgnH);
    uint8_t partBuf[rgnW * rgnH];
    memset(partBuf, 0xFF, sizeof(partBuf));
    drawPeriodLabel(partBuf, rgnPixelW, rgnH, 0, 0, rgnPixelW, rgnH);
    epdPartialDisplay(partBuf, TIME_RGN_X0, TIME_RGN_Y0, TIME_RGN_X1, TIME_RGN_Y1);
}

// ── Mode preview screen (double-click transition) ───────────

void showModePreview(const char *modeName) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);

    int nameScale = (H < 200) ? 1 : 2;
    int loadScale = 1;

    int nameX = (W - asciiTextWidth(modeName, nameScale)) / 2;
    int nameY = H / 2 - (H < 200 ? 15 : 30);
    drawText(modeName, nameX, nameY, nameScale);

    const char *loading = "loading...";
    int loadX = (W - asciiTextWidth(loading, loadScale)) / 2;
    int loadY = H / 2 + (H < 200 ? 10 : 20);
    drawText(loading, loadX, loadY, loadScale);

    epdDisplayFast(imgBuf);
    Serial.printf("Mode preview shown: %s\n", modeName);
}

// ── Smart display with hybrid refresh strategy ──────────────
// Uses fast refresh (0xC7 + temperature LUT, ~1.5s, minimal flash) most of the time.
// Performs a full refresh (0xF7, clears ghosting) every FULL_REFRESH_INTERVAL cycles.

static int refreshCount = 0;

void smartDisplay(const uint8_t *image) {
    // RLCD: every refresh is an equal full repaint (no fast/full LUT distinction,
    // no ghosting). The cycle counter is kept for API parity with e-ink builds.
    if (refreshCount % FULL_REFRESH_INTERVAL == 0) {
        Serial.printf("smartDisplay: full repaint (cycle %d)\n", refreshCount);
        epdDisplay(image);
    } else {
        Serial.printf("smartDisplay: fast repaint (cycle %d)\n", refreshCount);
        epdDisplayFast(image);
    }
    refreshCount++;
}

// ── UI chrome: status bar / 7-seg clock / todo rows / footer ──
// Three fixed layers (top status bar, middle todo list, bottom footer),
// pixel / ink style: pure black-on-white, thin solid rules, dashed dividers.

#define UI_SB_H   52      // status bar height
#define UI_FT_H   26      // footer height (taller, top border raised)
#define UI_ROW_H  30      // todo row height
#define UI_PER_PAGE 6     // todo items per page (fixed)

// Hollow rectangle outline (thin 1px rule).
static void outlineRect(int x, int y, int w, int h) {
    int rowBytes = W / 8;
    for (int xx = x; xx < x + w; xx++) {
        if (y >= 0 && y < H)        imgBuf[y*(rowBytes) + xx/8] &= ~(0x80 >> (xx%8));
        if (y+h-1 >= 0 && y+h-1 < H) imgBuf[(y+h-1)*(rowBytes) + xx/8] &= ~(0x80 >> (xx%8));
    }
    for (int yy = y; yy < y + h; yy++) {
        if (x >= 0 && x < W)         imgBuf[yy*(rowBytes) + x/8] &= ~(0x80 >> (x%8));
        if (x+w-1 >= 0 && x+w-1 < W) imgBuf[yy*(rowBytes) + (x+w-1)/8] &= ~(0x80 >> ((x+w-1)%8));
    }
}

// ── pixel fill helper ───────────────────────────────────────
static void segFill(int x, int y, int sw, int sh) {
    int rowBytes = W / 8;
    for (int yy = y; yy < y + sh; yy++)
        for (int xx = x; xx < x + sw; xx++) {
            int px = x + xx, py = y + yy;
            if (px >= 0 && px < W && py >= 0 && py < H)
                imgBuf[py*rowBytes + px/8] &= ~(0x80 >> (px%8));
        }
}

// ── Pixel icons ─────────────────────────────────────────────
static void drawCheckbox(int x, int y, bool checked) {
    outlineRect(x, y, 14, 14);
    if (checked) {                                  // simple check mark
        int pts[][2] = {{3,9},{4,10},{5,11},{6,10},{7,9},{8,8},{9,7},{10,6},{11,5},{5,7},{6,7},{7,7},{8,7}};
        int n = (int)(sizeof(pts) / sizeof(pts[0]));
        for (int k = 0; k < n; k++) {
            int px = x + pts[k][0], py = y + pts[k][1];
            if (px >= 0 && px < W && py >= 0 && py < H)
                imgBuf[py*(W/8) + px/8] &= ~(0x80 >> (px%8));
        }
    }
}

static void drawMiniList(int x, int y) {
    for (int r = 0; r < 3; r++) {
        outlineRect(x, y+r*6, 4, 4);
        int yy = y + r*6 + 2;
        for (int xx = x+6; xx < x+14; xx++)
            if (yy >= 0 && yy < H) imgBuf[yy*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
    }
}

static const char *WEEKDAY_CN[7] = {
    "星期日","星期一","星期二","星期三","星期四","星期五","星期六"
};

// ── Status bar ──────────────────────────────────────────────
static void drawStatusBar(int batteryPct, bool wifiConnected) {
    // Clock + date both read from the system RTC (kept accurate by syncNTP).
    time_t now = time(nullptr);
    struct tm ti; localtime_r(&now, &ti);
    int lineY = (UI_SB_H - 16) / 2;            // vertically center the 16px line
    // Clock as plain proportional ASCII "HH:MM" (same size as body text)
    char hhmm[6];
    snprintf(hhmm, sizeof(hhmm), "%02d:%02d", ti.tm_hour, ti.tm_min);
    int cx = 4;
    for (char *p = hhmm; *p; p++) {
        const uint32_t *g = ascii18_lookup((uint8_t)*p);
        if (g) drawAscii18(cx, lineY - ASCII18_CAP, g, 1);
        cx += ascii18_width[(uint8_t)*p - ASCII18_FIRST] + 1;
    }
    // date: 月/日 星期X (right of the clock, same baseline; 16px CJK + 8px ASCII)
    char date[32];
    snprintf(date, sizeof(date), "%02d/%02d %s",
             ti.tm_mon + 1, ti.tm_mday, WEEKDAY_CN[ti.tm_wday % 7]);
    drawMixed(cx + 6, lineY, date, 1);

    // ── Right side: WiFi icon (when connected) + "电量：xx%" ──
    char batt[16];
    snprintf(batt, sizeof(batt), "电量:%d%%", batteryPct);
    int battW = measureMixed(batt, 1);          // CJK + half-width ASCII
    int wifiW = 16, gap = 6;
    int rightX = W - 4;                          // right margin
    int blockW = (wifiConnected ? (wifiW + gap) : 0) + battW;
    int curX = rightX - blockW;
    if (wifiConnected) {
        drawGlyph16(imgBuf, W, H, curX, lineY, GLYPH_WIFI);
        curX += wifiW + gap;
    }
    drawMixed(curX, lineY, batt, 1);

    // separator rule under status bar
    for (int xx = 0; xx < W; xx++)
        if (UI_SB_H >= 0 && UI_SB_H < H) imgBuf[UI_SB_H*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
}

// ── Todo list (middle) ──────────────────────────────────────
static void drawTodoList(const TodoItem *items, int count) {
    int y0 = UI_SB_H + 4;
    for (int i = 0; i < count; i++) {
        int rowTop = y0 + i * UI_ROW_H;
        drawCheckbox(8, rowTop + (UI_ROW_H - 14) / 2, items[i].done);
        // body text (CJK+ASCII), truncate so it never collides with remind time
        int maxW = W - 30 - 58 - 6;
        String t = String(items[i].text);
        while (measureMixed(t.c_str(), 2) > maxW && t.length() > 1)
            t = t.substring(0, t.length() - 1);
        drawMixed(30, rowTop + (UI_ROW_H - 16) / 2, t.c_str(), 2);
        // reminder time (right aligned, pure ASCII, no CJK top offset)
        if (items[i].remind) {
            int rw = measureMixed(items[i].remind, 1);
            // cap-top aligned with the body text (same y as drawMixed above)
            drawAsciiText(W - 6 - rw - 1, rowTop + (UI_ROW_H - 16) / 2, items[i].remind, 1);
        }
        // dashed divider between rows
        if (i < count - 1)
            for (int xx = 8; xx < W - 6; xx += 4)
                if (rowTop + UI_ROW_H - 5 >= 0 && rowTop + UI_ROW_H - 5 < H)
                    imgBuf[(rowTop + UI_ROW_H - 5)*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
    }
}

// ── Footer ──────────────────────────────────────────────────
static void drawFooter() {
    int fy = H - UI_FT_H;                          // top border of footer
    for (int xx = 0; xx < W; xx++)
        if (fy >= 0 && fy < H) imgBuf[fy*(W/8) + xx/8] &= ~(0x80 >> (xx%8));
    int contentY = H - UI_FT_H + (UI_FT_H - 16) / 2;   // vertically center 16px line
    drawMiniList(8, contentY + 1);
    drawMixed(24, contentY, "待办", 1);           // wider gap after the mini-list icon
    drawMixed(W - 6 - measureMixed("— 诸事有序", 1) - 1, contentY, "— 诸事有序", 1);
}

// ── Composite native todo screen ────────────────────────────
void renderTodoScreen(const TodoItem *items, int count, int page, int totalPages, int batteryPct, bool wifiConnected, bool autoDisplay) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);
    drawStatusBar(batteryPct, wifiConnected);
    drawTodoList(items, count);
    drawFooter();
    // pagination hint (bottom-right of content area, pure ASCII, no offset)
    char pg[16];
    snprintf(pg, sizeof(pg), "%d / %d", page + 1, totalPages);
    int pgw = measureMixed(pg, 1);
    drawAsciiText(W - 6 - pgw - 1, H - UI_FT_H - 24, pg, 1);
    if (autoDisplay) smartDisplay(imgBuf);
}

// ── Settings menu (two-level) ──────────────────────────────
// 一级（左侧）: 系统设置 | 二级（右侧）: 重新配网 / 本机MAC地址 / 当前WiFi名称
static const char *SETTINGS_ITEM_LABELS[3] = {
    "重新配网", "本机 MAC 地址", "当前 WiFi 名称"
};

void renderSettingsScreen(int cursor, int detail, int batteryPct, bool wifiConnected) {
    memset(imgBuf, 0xFF, IMG_BUF_LEN);
    drawStatusBar(batteryPct, wifiConnected);

    int top = UI_SB_H + 12;
    // 一级菜单（左侧）
    drawMixed(8, top, "系统设置", 2);
    // vertical divider between 一级 (left) and 二级 (right)
    int divX = W * 34 / 100;
    for (int yy = top; yy < top + 3 * UI_ROW_H + 20; yy++)
        if (yy >= 0 && yy < H) imgBuf[yy * (W / 8) + divX / 8] &= ~(0x80 >> (divX % 8));

    // 二级菜单（右侧）
    int rx = divX + 12;
    int ry0 = top + 6;
    for (int i = 0; i < 3; i++) {
        int ry = ry0 + i * UI_ROW_H;
        if (i == cursor) {
            // selection cursor: filled block immediately left of the item
            segFill(rx - 11, ry + 4, 6, 8);
        }
        drawMixed(rx, ry + 4, SETTINGS_ITEM_LABELS[i], 1);
    }

    // detail box for read-only info items (MAC address / current WiFi name)
    if (detail == 1 || detail == 2) {
        int dy = top + 3 * UI_ROW_H + 8;       // sits below the list, above the hint
        outlineRect(8, dy, W - 16, 58);        // taller: ascii18 value line is 20px
        const char *label = (detail == 1) ? "本机 MAC 地址" : "当前 WiFi 名称";
        String val = (detail == 1) ? WiFi.macAddress()
                                    : (WiFi.SSID().length() ? WiFi.SSID() : "未连接");
        drawMixed(16, dy + 8, label, 1);
        drawMixed(16, dy + 32, val.c_str(), 1);
    }

    // key hint (just above the footer; raised so the 20px ascii doesn't reach the footer rule)
    drawMixed(8, H - UI_FT_H - 28, "BOOT:下一项  KEY:确认 / 长按进出", 1);

    // footer rule + settings-specific label
    int fy = H - UI_FT_H;
    for (int xx = 0; xx < W; xx++)
        if (fy >= 0 && fy < H) imgBuf[fy * (W / 8) + xx / 8] &= ~(0x80 >> (xx % 8));
    int contentY = H - UI_FT_H + (UI_FT_H - 16) / 2;
    drawMixed(8, contentY, "设置", 1);
    drawMixed(W - 6 - measureMixed("— InkSight —", 1) - 1, contentY, "— InkSight —", 1);
}
